return {
    { "blink.cmp", version = "*" },
    { "catppuccin", version = "*" },
    { "codediff.nvim", version = "*" },
    { "dial.nvim", version = "*" },
    { "gitsigns.nvim", version = "*" },
    { "grug-far.nvim", version = "*" },
    { "img-clip.nvim", version = "*" },
    { "kulala.nvim", version = "*" },
    { "live-preview.nvim", commit = "c1fcf75" },
    { "mason-lspconfig.nvim", lazy = true, version = "*" },
    { "mason-null-ls.nvim", version = "*" },
    { "mason.nvim", lazy = true, version = "*" },
    { "mini.ai", version = "*" },
    { "mini.basics", version = "*" },
    { "mini.bracketed", version = "*" },
    { "mini.hipatterns", version = "*" },
    { "mini.icons", version = "*" },
    { "mini.move", version = "*" },
    { "mini.splitjoin", version = "*" },
    { "mini.surround", version = "*" },
    { "minuet-ai.nvim", version = "*" },
    { "molten-nvim", version = "^1.0.0" },
    { "nvim-dap", lazy = true, commit = "7bb46cc" },
    { "nvim-java", version = "*" },
    { "nvim-java-core", version = "*", ft = "java" },
    { "nvim-java-dap", version = "*", ft = "java" },
    { "nvim-java-refactor", version = "*", ft = "java" },
    { "nvim-java-test", version = "*", ft = "java" },
    { "nvim-lspconfig", version = "*" },
    { "nvim-treesitter-context", branch = "master" },
    { "nvim-treesitter-locals", version = "*" },
    { "nvim-treesitter-textobjects", branch = "main" },
    { "oil.nvim", version = "*" },
    { "otter.nvim", version = "*" },
    { "overseer.nvim", version = "*" },
    { "render-markdown.nvim", version = "*" },
    { "sidekick.nvim", version = "*" },
    { "snacks.nvim", version = "*" },
    { "snap.nvim", version = "*" },
    { "sniprun", version = "*" },
    { "ultimate-autopair.nvim", branch = "v0.6" },
    { "which-key.nvim", version = "^3.0.0" },

    -- { "blink-nerdfont.nvim", version = "*" },
    -- { "colorful-menu.nvim", version = "*" },
    -- { "devdocs.nvim", version = "*" },
    -- { "emmet-vim", version = "*" },
    -- { "faster.nvim", version = "*" },
    -- { "flash.nvim", version = "*" },
    -- { "friendly-snippets", version = "*" },
    -- { "jupytext.nvim", version = "*" },
    -- { "lazydev.nvim", version = "*" },
    -- { "lspsaga.nvim", version = "*" },
    -- { "lualine.nvim", version = "*" },
    -- { "mason-null-ls.nvim", version = "*" },
    -- { "multicursor.nvim", version = "*" },
    -- { "neogen", version = "*" },
    -- { "neogit", version = "*" },
    -- { "noice.nvim", version = "*" },
    -- { "none-ls-extras.nvim", version = "*" },
    -- { "none-ls.nvim", version = "*" },
    -- { "nui.nvim", version = "*" },
    -- { "nvim-bqf", version = "*" },
    -- { "nvim-dap-disasm", version = "*" },
    -- { "nvim-dap-view", version = "*" },
    -- { "nvim-nio", version = "*" },
    -- { "nvim-spider", version = "*" },
    -- { "nvim-treesitter", version = "*" },
    -- { "nvim-ts-autotag", version = "*" },
    -- { "plenary.nvim", version = "*" },
    -- { "rainbow-delimiters.nvim", version = "*" },
    -- { "spring-boot.nvim", version = "*" },
    -- { "suda.vim", version = "*" },
    -- { "supermaven-nvim", version = "*" },
    -- { "tree-sitter-manager.nvim", version = "*" },
    -- { "vim-dadbod", version = "*" },
    -- { "vim-dadbod-completion", version = "*" },
    -- { "vim-dadbod-ui", version = "*" },
    -- { "vim-tmux-navigator", version = "*" },
}
