return {
    { "blink.cmp", version = "^1.10.2" },
    { "catppuccin", version = "^2.0.0" },
    { "codediff.nvim", version = "^2.43.15" },
    { "dial.nvim", version = "*" },
    { "gitsigns.nvim", version = "^2.1.0" },
    { "grug-far.nvim", version = "^1.6.67" },
    { "img-clip.nvim", version = "*" },
    { "kulala.nvim", version = "^5.3.4" },
    { "mason-lspconfig.nvim", version = "^2.2.0" },
    { "mason-null-ls.nvim", version = "^2.6.0" },
    { "mason.nvim", version = "^2.2.1" },
    { "mini.ai", version = "*" },
    { "mini.basics", version = "*" },
    { "mini.bracketed", version = "*" },
    { "mini.hipatterns", version = "*" },
    { "mini.icons", version = "*" },
    { "mini.move", version = "*" },
    { "mini.splitjoin", version = "*" },
    { "mini.surround", version = "*" },
    { "minuet-ai.nvim", version = "*" },
    { "molten-nvim", version = "^1.9.2" },
    { "nvim-dap-view", version = "^1.1.1" },
    { "nvim-java", version = "^4.1.0" },
    { "nvim-java-core", version = "*", ft = "java" },
    { "nvim-java-dap", version = "*", ft = "java" },
    { "nvim-java-refactor", version = "*", ft = "java" },
    { "nvim-java-test", version = "*", ft = "java" },
    { "nvim-lspconfig", version = "^2.8.0" },
    { "nvim-treesitter-locals", version = "*" },
    { "oil.nvim", version = "^2.15.0" },
    { "otter.nvim", version = "^2.14.5" },
    { "overseer.nvim", version = "^2.1.0" },
    { "render-markdown.nvim", version = "^8.12.0" },
    { "sidekick.nvim", version = "^2.3.0" },
    { "snacks.nvim", version = "^2.31.0" },
    { "snap.nvim", version = "^1.5.0" },
    { "sniprun", version = "^1.3.22" },
    { "which-key.nvim", version = "^3.17.0" },

    { "nvim-treesitter-context", branch = "master" },
    { "nvim-treesitter-textobjects", branch = "main" },
    { "ultimate-autopair.nvim", branch = "v0.6" },

    { "live-preview.nvim", commit = "c1fcf75" },
    { "nvim-dap", commit = "45a69eb" },
    { "vim-suda", commit = "c492741" },

    -- { "blink-nerdfont.nvim", version = "*" },
    -- { "colorful-menu.nvim", version = "*" },
    -- { "devdocs.nvim", version = "*" },
    -- { "emmet-vim", version = "*" },
    -- { "faster.nvim", version = "*" },
    -- { "flash.nvim", version = "*" },
    -- { "friendly-snippets", version = "*" },
    -- { "jupytext.nvim", version = "*" },
    -- { "lazydev.nvim", version = "*" },
    -- { "lualine.nvim", version = "*" },
    -- { "mason-null-ls.nvim", version = "*" },
    -- { "multicursor.nvim", version = "*" },
    -- { "neogen", version = "*" },
    -- { "neogit", version = "*" },
    -- { "noice.nvim", version = "*" },
    -- { "none-ls-extras.nvim", version = "*" },
    -- { "none-ls.nvim", version = "*" },
    -- { "nui.nvim", version = "*" },
    -- { "nvim-bqf", version = "*" },
    -- { "nvim-dap-disasm", version = "*" },
    -- { "nvim-nio", version = "*" },
    -- { "nvim-spider", version = "*" },
    -- { "nvim-treesitter", version = "*" },
    -- { "nvim-ts-autotag", version = "*" },
    -- { "plenary.nvim", version = "*" },
    -- { "rainbow-delimiters.nvim", version = "*" },
    -- { "spring-boot.nvim", version = "*" },
    -- { "supermaven-nvim", version = "*" },
    -- { "tree-sitter-manager.nvim", version = "*" },
    -- { "vim-dadbod", version = "*" },
    -- { "vim-dadbod-completion", version = "*" },
    -- { "vim-dadbod-ui", version = "*" },
    -- { "vim-tmux-navigator", version = "*" },
}
